### ISSUE TITLE
Development Workflow: branches

### ISSUE THREAD

**Issue by rmariuzzo** [rmariuzzo/Laravel-JS-Localization#32]
Hey team! I'm thinking on how we should manages versions within our repo. As this package is similar to Laravel, I would consider following [their guide](http://laravel.com/docs/5.1/contributions#which-branch).

We would end up with the following branches:
 - **`master`** — upcoming version.
 - **`5.1`** — Laravel 5.1 compatible version.
 - **`5.0`** — Laravel 5.0 compatible version.
 - **`4.2`** — Laravel 4.2 compatible version.

Additional branches:
 - Bug fixes — `5.1/fix/issue-1`, `5.0/fix/another-issue` and so on.
 - Features — `feature/superpower`, `feature/simple-power` and so on.

All major feature should be merged to `master` (upcoming version). All minor feature should be merged to a particular version _and_ backward compatibility to previous version.

What do you think? @vluzrmos @gpopoteur @okaufmann @xAockd

**Comment by vluzrmos** [comment]
I think if the branch is not the version of the package, it need to be more explicit in its proposal, like:

**laravel-5.1**
**laravel-5.0**
**laravel-4.2**

I recommend you to use branchs with the package versions, instead of the compatibility with laravel. On readme.md of the master branch should be described which branch is for each laravel version.

**Comment by rmariuzzo** [comment]
Good one! I like your recommendation.

**Comment by okaufmann** [comment]
Nothing left to say @vluzrmos !

**Comment by rmariuzzo** [comment]
Hey @a-komarev! What do you think on having branches per Laravel versions? Do you think it is necessary?

**Comment by a-komarev** [comment]
@rmariuzzo It's not a bad idea, I'll write some thoughts related to this way.

In my vision there is a need to create separate branch for each concrete Laravel version if there is no way to support it in current one or if it will bring a lot of hacks to work both ways. For example if you need to support Laravel 4.x it's good idea to hold it separately, because there were a lot of changes in API and it could be redunant to maintain it in master. *By the master branch I assume package's version branches `1.0`, `2.0` and so on.*

But if you will create a branch for each Laravel version in future it will be harder and harder to maintain because if you'll make a changes - you will require to replicate them in every single branch for each Laravel versions, but in most cases all the versions will have same code and could work with master branch without any issues.

And what if you are releasing version `2.0` of package. It will be available in branch `2.0` and in all `laravel-*` branches versions? How would it be possible to stay on `v1.0` of the package?

Usually I see that people just writing in README that for `4.x` support you should use branch `laravel-4` or branch `1.2` because newer branches are dropped old Laravel versions support, for all other Laravel versions user should use default packages master branches.

Official Laravel packages branching example:

- https://github.com/laravel/cashier/branches
- https://github.com/laravel/socialite/branches

**Comment by rmariuzzo** [comment]
@a-komarev I appreciate your thoughts on this. I agree with you in all points:

 - Support Laravel 5 version in `master` branch, since the API doesn't change too much.
 - Support Laravel 4 version in a `laravel-4` branch.
 - Use `laravel-` prefix to avoid confusion with package versions.

For `laravel-js-localization` package the main differences between Laravel 4 and Laravel 5 is the default location of lang files (`app/lang` vs `resources/lang`). Also, the API for the `Illuminate\Console\Command` has some changes.

However, most of the codebase of `laravel-js-localization` is Laravel agnostic. So, I'm willing to try to make `laravel-js-localization` compatible with Laravel 4 + Laravel 5. The first version worked flawlessly. I will play today with it and look how to test the package against different Laravel versions.

**Comment by rmariuzzo** [comment]
@a-komarev as you pointed, there's no need to have separate branches. We will still follow the Branch workflow using `master` and `develop`.
